apiVersion: v1
kind: Service
metadata:
  name: {{ include "two-tier-app.frontendName" . }}
  labels:
    {{- include "two-tier-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "two-tier-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
