name: Build And Deploy To EKS

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "helm/two-tier-app/**"
      - ".github/workflows/build-and-deploy.yml"

  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      image-tag: ${{ steps.image.outputs.image-tag }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        id: image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build Backend Image
        run: |
          docker build \
          -t $DOCKER_USERNAME/employee-management-backend:${{ steps.image.outputs.image-tag }} \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t $DOCKER_USERNAME/employee-management-frontend:${{ steps.image.outputs.image-tag }} \
          ./frontend

      - name: Push Backend Image
        run: |
          docker push \
          $DOCKER_USERNAME/employee-management-backend:${{ steps.image.outputs.image-tag }}

      - name: Push Frontend Image
        run: |
          docker push \
          $DOCKER_USERNAME/employee-management-frontend:${{ steps.image.outputs.image-tag }}

  deploy-dev:
    name: Deploy To DEV
    runs-on: ubuntu-latest

    needs:
      - build-and-push

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region "$AWS_REGION" \
          --name "$EKS_CLUSTER_NAME"

      - name: Debug Image Tag
        run: |
          echo "Image Tag = ${{ needs.build-and-push.outputs.image-tag }}"

      - name: Deploy Application To DEV
        run: |
          helm upgrade --install two-tier-app-dev ./helm/two-tier-app \
          --namespace dev \
          --create-namespace \
          -f ./helm/two-tier-app/values-dev.yaml \
          --wait \
          --timeout 10m \
          --set backend.image.repository="$DOCKER_USERNAME/employee-management-backend" \
          --set backend.image.tag="${{ needs.build-and-push.outputs.image-tag }}" \
          --set frontend.image.repository="$DOCKER_USERNAME/employee-management-frontend" \
          --set frontend.image.tag="${{ needs.build-and-push.outputs.image-tag }}"

      - name: Verify DEV Deployment
        run: |
          kubectl get pods -n dev
          kubectl get svc -n dev
          kubectl get deployments -n dev

  deploy-uat:
    name: Deploy To UAT
    runs-on: ubuntu-latest

    needs:
      - build-and-push
      - deploy-dev

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region "$AWS_REGION" \
          --name "$EKS_CLUSTER_NAME"

      - name: Debug Image Tag
        run: |
          echo "Image Tag = ${{ needs.build-and-push.outputs.image-tag }}"

      - name: Deploy Application To UAT
        run: |
          helm upgrade --install two-tier-app-uat ./helm/two-tier-app \
          --namespace uat \
          --create-namespace \
          -f ./helm/two-tier-app/values-uat.yaml \
          --wait \
          --timeout 10m \
          --set backend.image.repository="$DOCKER_USERNAME/employee-management-backend" \
          --set backend.image.tag="${{ needs.build-and-push.outputs.image-tag }}" \
          --set frontend.image.repository="$DOCKER_USERNAME/employee-management-frontend" \
          --set frontend.image.tag="${{ needs.build-and-push.outputs.image-tag }}"

      - name: Verify UAT Deployment
        run: |
          kubectl get pods -n uat
          kubectl get svc -n uat
          kubectl get deployments -n uat

  deploy-prod:
    name: Deploy To PROD
    runs-on: ubuntu-latest

    needs:
      - build-and-push
      - deploy-uat

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region "$AWS_REGION" \
          --name "$EKS_CLUSTER_NAME"

      - name: Debug Image Tag
        run: |
          echo "Image Tag = ${{ needs.build-and-push.outputs.image-tag }}"

      - name: Deploy Application To PROD
        run: |
          helm upgrade --install two-tier-app-prod ./helm/two-tier-app \
          --namespace prod \
          --create-namespace \
          -f ./helm/two-tier-app/values-prod.yaml \
          --wait \
          --timeout 10m \
          --set backend.image.repository="$DOCKER_USERNAME/employee-management-backend" \
          --set backend.image.tag="${{ needs.build-and-push.outputs.image-tag }}" \
          --set frontend.image.repository="$DOCKER_USERNAME/employee-management-frontend" \
          --set frontend.image.tag="${{ needs.build-and-push.outputs.image-tag }}"

      - name: Verify PROD Deployment
        run: |
          kubectl get pods -n prod
          kubectl get svc -n prod
          kubectl get deployments -n prod