name: Validate Helm Chart

on:
  pull_request:
    branches:
      - main
    paths:
      - "helm/two-tier-app/**"
      - ".github/workflows/helm-validate.yml"

  workflow_dispatch:

jobs:

  helm-validate:
    name: Helm Lint and Template Validation
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: |
          helm lint ./helm/two-tier-app

      - name: Helm Template Render Validation
        run: |
          helm template two-tier-app ./helm/two-tier-app > rendered-output.yaml

      - name: Validate DEV Values
        run: |
          helm template two-tier-app ./helm/two-tier-app \
          -f ./helm/two-tier-app/values-dev.yaml > dev-rendered.yaml

      - name: Validate UAT Values
        run: |
          helm template two-tier-app ./helm/two-tier-app \
          -f ./helm/two-tier-app/values-uat.yaml > uat-rendered.yaml

      - name: Validate PROD Values
        run: |
          helm template two-tier-app ./helm/two-tier-app \
          -f ./helm/two-tier-app/values-prod.yaml > prod-rendered.yaml